### ISSUE TITLE
Huge amount of CGI_NO_SERVER errors in the log

### ISSUE THREAD

**Issue by MTRNord** [derhuerst/nahsh-gtfs-rt-server#3]
```
Nov 01 16:38:20 nordgedanken.dev start.sh[341215]: {"level":40,"time":1635781100409,"pid":341215,"name":"monitor","isHafasError":true,"request":"{\"lang\":\"de\",\"svcReqL\":[{\"meth\":\"JourneyGeoPos\",\"req\":{\"maxJny\":1000,\"onlyRT\":false,\"date\":\"20211101\",\"time\":\"163722\",\"rect\":{\"llCrd\":{\"x\":8950361,\"y\":53646146},\"urCrd\":{\"x\":9025714,\"y\":53691112}},\"perSize\":0,\"perStep\":0,\"ageOfReport\":true,\"jnyFltrL\":[{\"type\":\"PROD\",\"mode\":\"INC\",\"value\":\"1023\"}],\"trainPosMode\":\"CALC\"}}],\"client\":{\"type\":\"IPH\",\"id\":\"NAHSH\",\"v\":\"3000700\",\"name\":\"NAHSHPROD\"},\"ver\":\"1.30\",\"auth\":{\"type\":\"AID\",\"aid\":\"r0Ot9FLFNAFxijLW\"}}","url":"https://nah.sh.hafas.de/bin/mgate.exe?","statusCode":200,"code":"CGI_NO_SERVER","message":"CGI_NO_SERVER","responseId":null,"stack":"Error: CGI_NO_SERVER\n    at Object.request (/opt/nahsh-gtfs-rt-server/node_modules/hafas-client/lib/request.js:109:14)\n    at Timeout.execute [as _onTimeout] (/opt/nahsh-gtfs-rt-server/node_modules/p-throttle/index.js:75:24)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)","type":"Error","msg":"CGI_NO_SERVER"}
```

I am assuming due to https://github.com/public-transport/hafas-client/issues/232 that this can be ignored but I want to double check. Is this expected or is this some kind of setup misstake on my side?

**Comment by derhuerst** [comment]
You could investigate if it always happens after/with a specific call, which crashes the backend, but other than that, AFAICT there is nothing you can do about it. Sorry.
